name: Cloud check in action
on:
  push:
    branches:
      - main
  watch:
    types: started
  workflow_dispatch:
  schedule:
    - cron: 55 3 * * *
    # 显式声明权限，确保可以删除运行记录和更新仓库活跃度
permissions:
  contents: write
  actions: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: user
    steps:
      - name: 🔌 Check out code
        uses: actions/checkout@main

      - name: 🔨 Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: npm

      - name: 👾 Check if Debug is true
        if: vars.debug == '1'
        run: |
          echo "CLOUD189_VERBOSE=1" >> $GITHUB_ENV
      
      - name: 📹 Restore cached Cookie
        id: cache-cookie-restore
        uses: actions/cache/restore@v4
        with:
          path: .token
          key: ${{ runner.os }}-cache-token
          restore-keys: ${{ runner.os }}-cache-token-

      - name: 🔧 Init secrets
        uses: shine1594/secrets-to-env-action@master
        with:
          secrets: ${{ toJSON(secrets) }}
          secrets_env: production
          prefix_prod: ""
          file_name_prod: .env

      - name: 📡 Init dependencies
        run: npm install

      - name: 🚀 Run
        uses: nick-fields/retry@master
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: npm start
      
      - name: 📹 Save cached Cookie
        uses: actions/cache/save@v4
        with:
          path: .token
          key: ${{ runner.os }}-cache-token-${{ hashFiles('.token/*.json') }}

      - name: 🎉 Delete old workflow run
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 50
      # ================= 新增步骤：防止 GitHub 自动禁用脚本 =================
      - name: 🔄 Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: true # 使用 API 更新活跃度，不会产生无用的 commit
      # ==================================================================
          
